// Minimal mapping. Lessons can override via lesson.emoticonMap.
export const defaultBeatEmoticon: Record<string, string> = {
  action: "🔨",
  decision: "✅",
  desire: "❤️",
  conflict: "⚔️",
  obstacle: "🧱",
  climax: "⛰️",
  resolution: "🌅",
  reveal: "👁️",
  realization: "💡",
  exposition: "📜",
  foreshadow: "🌒",
  setup: "🎯",
  payoff: "🎉",
  emotion: "😭",
  suppression: "🤐",
  vulnerability: "🫀",
  power: "👑",
  shift: "🔄",
  intimacy: "🤝",
  alienation: "🪫",
  dialogue: "💬",
  nonverbal: "👀",
  interaction: "↔️",
  agreement: "✍️",
  disagreement: "❌",
  test: "🧪",
  reversal: "🔁",
  atmosphere: "🌫️",
  discovery: "🗺️",
  loss: "🕳️",
  arrival: "🚪",
  departure: "🛫",
  transition: "⏭️",
  inciting: "⚡",
  "turning point": "🔀",
  mirror: "🪞",
  bridge: "🌉",
  suspense: "⏳",
  release: "💨",
  "thematic statement": "📢",
  counterpoint: "↕️",
  "test of belief": "🧭",
  transformation: "🦋",
  "mirror (thematic)": "🪞✨",
  sacrifice: "🔥",
  "revelation (thematic)": "✨",
  "resolution (thematic)": "🏁"
};

export function emojiForBeat(id: string, override?: Record<string, string>) {
  const key = id.toLowerCase();
  return (override && override[key]) || defaultBeatEmoticon[key] || "⬛";
}
