export const BEAT_SYNONYMS = {
    action: ["act", "move", "do"],
    decision: ["choose", "choice", "decide"],
    desire: ["want", "need", "goal", "longing"],
    conflict: ["clash", "versus", "vs", "tension"],
    obstacle: ["block", "barrier", "problem"],
    reveal: ["twist", "truth", "discovery"],
    realization: ["epiphany", "understand"],
    exposition: ["info", "explain"],
    foreshadow: ["hint", "omen"],
    setup: ["plant", "seed"],
    payoff: ["return", "callback"],
    emotion: ["feeling", "affect"],
    suppression: ["hide", "mask"],
    vulnerability: ["open", "risk"],
    power: ["status", "control"],
    shift: ["flip", "turn"],
    intimacy: ["closeness", "tender"],
    alienation: ["distance", "withdraw"],
    dialogue: ["talk", "speech", "line"],
    nonverbal: ["gesture", "look", "silence"],
    interaction: ["exchange", "beat"],
    agreement: ["align", "consent"],
    disagreement: ["argue", "rift"],
    test: ["probe", "challenge"],
    reversal: ["invert", "surprise"],
    atmosphere: ["mood", "vibe", "weather"],
    discovery: ["find", "reveal object"],
    loss: ["remove", "gone"],
    arrival: ["enter", "come"],
    departure: ["leave", "exit"],
    transition: ["cut", "dissolve"],
    inciting: ["spark", "trigger"],
    "turning point": ["pivot", "swerve"],
    mirror: ["echo", "repeat"],
    bridge: ["link", "between"],
    suspense: ["delay", "hang"],
    release: ["relief", "resolve"],
    "thematic statement": ["theme", "claim"],
    counterpoint: ["contradict", "against"],
    "test of belief": ["values", "principle"],
    transformation: ["change", "shift self"],
    "thematic mirror": ["echo theme", "prove"],
    sacrifice: ["cost", "give up"],
    "thematic revelation": ["core truth"],
    "thematic resolution": ["final stance"],
};
