export { default as Home } from "./Home";
export { default as PackPage } from "./Pack";
export { default as PracticePage } from "./Practice";
export { default as PracticeHub } from "./Play";
export { default as Settings } from "./Settings";
export { default as PlaySee } from "./PlaySee";
export { default as PlayMCQ } from "./PlayMCQ";
export { default as PlaySlot } from "./PlaySlot";
export { default as NotFound } from "./NotFound";
