name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build (Vite)
        env:
          GHPAGES_REPO: projects-from-the-projects
          GHPAGES_BASE: /projects-from-the-projects/
        run: npm run build

      - name: Run Lighthouse CI (static dist)
        run: |
          npx @lhci/cli@0.13.x autorun \
            --config=./lighthouserc.json \
            --upload.target=temporary-public-storage
